name: DAHLIA+
favicon: null
layout_spectrum: 0.67488
typography_spectrum: 0.52066
title: DAHLIA+
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121011'
    - '#179aa4'
    - '#5c5a5b'
    - '#f64b20'
  brandStrength: 0.625
  lightness: 0.6657639381010085
  saturation: 0.6298999476712197
  rhythmicContrast: 0.3130857015494257
purpose: []
