name: DAHLIA+
favicon: null
layout_spectrum: 0.67488
typography_spectrum: 0.52066
title: DAHLIA+
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121011'
    - '#179aa4'
    - '#5c5a5b'
    - '#f64b20'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
